config/routes.rb
Rails.application.routes.draw do
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
  def show
    @article = Article.find(params[:id])
  end
  def new
    @article = Article.new
  end

  def create
    Article.create(article_params)
    redirect_to articles_path
  end
  def edit
      @article = Article.find(params[:id])
  end
  def update
      @article = Article.find(params[:id])
      @article.update(article_params)
      redirect_to articles_path(@article)
  end

  def destroy
      @article = Article.find(params[:id])
      @article.destroy
      redirect_to articles_path

  end
private
  def article_params
    params.require(:article).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/views/articles/edit.html.erb
<%=form_for(@article) do |f| %>
 <%= f.label :title %>
 <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.submit %>
<% end %>

app/views/articles/index.html.erb
<h1>All our articles</h1>
<% @articles.each do |t|%>
<p><%=t.title%></p>
<p><%=t.content%></p>
<%= link_to "more details", article_path(t) %>
<%=link_to "delete", article_path(t), method: :delete %>
<%end%>

app/views/articles/new.html.erb
<%= form_for(@task) do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit %>
<% end %>

app/views/articles/show.html.erb
<h1><%=@article.title%></h1>
<h1><%=@article.content%></h1>
<%= link_to "back to all articles", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>